name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Doppler CLI
        run: |
          # Скачиваем и устанавливаем Doppler CLI с правами суперпользователя
          curl -sSfL https://cli.doppler.com/install.sh | sudo sh

      - name: Authenticate with Doppler
        run: doppler login --token ${{ secrets.DOPPLER_TOKEN }}

      - name: Use secrets
        run: |
          doppler run -- echo "Using secrets in the pipeline"
          doppler run -- echo "DB_PASSWORD=$DB_PASSWORD"
          doppler run -- echo "API_KEY=$API_KEY"
