name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Doppler CLI
        run: |
          # Скачиваем Doppler CLI
          curl -sSL https://cli.doppler.com/download/linux/amd64 -o doppler-cli.tar.gz
          # Распаковываем архив в директорию /usr/local/bin (или любую другую, доступную в PATH)
          tar -xvzf doppler-cli.tar.gz
          sudo mv doppler /usr/local/bin/  # Копируем в PATH для доступности

      - name: Authenticate with Doppler
        run: doppler login --token ${{ secrets.DOPPLER_TOKEN }}

      - name: Use secrets
        run: |
          doppler run -- echo "Using secrets in the pipeline"
          doppler run -- echo "DB_PASSWORD=$DB_PASSWORD"
          doppler run -- echo "API_KEY=$API_KEY"
