name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Doppler CLI
        uses: dopplerhq/doppler-action@v3
        with:
          doppler-token: ${{ secrets.DOPPLER_TOKEN }}
          project: ${{ secrets.DOPPLER_PROJECT }}

      - name: Use secrets
        run: |
          echo "Using secrets in the pipeline"
          echo "DB_PASSWORD=$DB_PASSWORD"
          echo "API_KEY=$API_KEY"
