name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Doppler and Fetch Secrets
        uses: dopplerhq/cli-action@v1
        with:
          doppler-token: ${{ secrets.DOPPLER_TOKEN }}
          mount-secrets: true 

      - name: Use secrets
        env:
          BOBRINA: ${{ env.BOBRINA }}
          ANIRBOB: ${{ env.ANIRBOB }}
        run: |
          echo "Здесь могла бы быть ваша реклама"
          echo "BOBRINA=$BOBRINA"
          echo "ANIRBOB=$ANIRBOB"
