on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v1 

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y nodejs npm 

      - name: Lint code
        run: |
          npm install eslint 

      - name: Run tests
        run: |
          npm test 
