name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Doppler CLI
        run: |
          curl -sSfL https://cli.doppler.com/install.sh | sudo sh

      - name: Authenticate with Doppler
        env:
          TOKEN: ${{ secrets.TOKEN }}
        run: |
          doppler setup --project ci-cd-study --config dev_personal

      - name: Use secrets
        env:
          TOKEN: ${{ secrets.TOKEN }}
        run: |
          doppler run -- echo "Здесь могла бы быть ваша реклама"
          doppler run -- echo "BOBRINA=$BOBRINA"
          doppler run -- echo "ANIRBOB=$ANIRBOB"
