name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Doppler CLI
        run: |
          # Скачиваем исполнимый файл Doppler CLI для Linux
          curl -sSL https://cli.doppler.com/download/linux/amd64 -o doppler
          # Даем права на выполнение файла
          chmod +x doppler
          # Перемещаем в директорию /usr/local/bin для доступности
          sudo mv doppler /usr/local/bin/

      - name: Authenticate with Doppler
        run: doppler login --token ${{ secrets.DOPPLER_TOKEN }}

      - name: Use secrets
        run: |
          doppler run -- echo "Using secrets in the pipeline"
          doppler run -- echo "DB_PASSWORD=$DB_PASSWORD"
          doppler run -- echo "API_KEY=$API_KEY"
