name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Doppler CLI
        uses: dopplerhq/cli-action@v1

      - name: Fetch secrets using Doppler
        run: |
          doppler run -- echo "Здесь могла бы быть ваша реклама" && \
          doppler run -- printenv | grep -E "BOBRINA|ANIRBOB"
