on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3  # Используйте последнюю версию

      - name: Set up Node.js
        uses: actions/setup-node@v3  # Настройка Node.js
        with:
          node-version: '14'  # Укажите версию Node.js

      - name: Install dependencies
        run: npm ci  # Используйте npm ci вместо npm install, если lock-файла нет, просто установите зависимости

      - name: Install ESLint
        run: npm install eslint --save-dev  # Установите ESLint как dev-зависимость

      - name: Lint code
        run: npx eslint .  # Запустите ESLint

      - name: Run tests
        run: npm test  # Запустите тесты
